service: my-lambda-service


provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
functions:
  hello:
    handler: dist/handler.handler
    events:
      - http:
          path: /
          method: get
